### ISSUE TITLE
Book a Time calendar opens in local timezone (sometimes?)

### ISSUE THREAD

**Issue by emilgoldsmith** [bnhopkins/Unix-Lab-Site#8]
Just something we should maybe figure out how to make sure the Google Calendar setting is correct, and then maybe write at the top of that page a small set of instructions to assure it is indeed correct.

Had a student come in today thinking she had an appointment when she had actually booked one of Simon's 12-1AM slots lol

**Comment by guyu96** [comment]
Related issue - I tried booking a time on the website and it just took me to a 400 error page.

**Comment by emilgoldsmith** [comment]
@guyu96 hmm well it's just an iframe to a google calendar so that should be Google's error really? 

Also, the student that came by had successfully booked so it's at least not a global issue
